language: swift
  
osx_image: xcode12

env:
  matrix:
    - TEST_SDK=iphonesimulator14.0 OS=14.0 NAME='iPhone 11'

script:
  - set -o pipefail && xcodebuild -workspace FoodApp.xcworkspace -scheme FoodApp -destination platform\=iOS\ Simulator,OS\=14.0,name\=iPhone\ 11 clean build | xcpretty
